apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "frontend.fullname" . }}-{{ .Values.deploymentColor }}"
  labels:
    app: {{ include "frontend.name" . }}
    color: "{{ .Values.deploymentColor }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "frontend.name" . }}
      color: "{{ .Values.deploymentColor }}"
  template:
    metadata:
      labels:
        app: {{ include "frontend.name" . }}
        color: "{{ .Values.deploymentColor }}"
    spec:
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
